trigger:
- main

pool:
  vmImage: windows-latest

steps:
- powershell: |
    $year = (Get-Date).ToString('yy')
    $month = (Get-Date).ToString('MM')
    $day = (Get-Date).ToString('dd')
    $version = "$year.$month.$day"
    Write-Host "##vso[task.setvariable variable=deployDate;]$version"
    dotnet pack Azure.Storage.Table.Repository/$(projectName).csproj -o $(Build.ArtifactStagingDirectory) --configuration Release --version $version --no-dependencies
  displayName: 'Pack Project'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGetOrgConnection'
  displayName: 'Push to NuGet'
