# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  deployDate: ''

pool:
  vmImage: windows-latest

jobs:
- job: Pack
  displayName: Pack Project
  continueOnError: false
  workspace:
    clean: outputs
  steps:
  - powershell: |
      $dateStr = (Get-Date).ToString('yyMMdd') 
      Write-Host "##vso[task.setvariable variable=deployDate;]$dateStr"
      dotnet pack Azure.Storage.Table.Repository/$(projectName).csproj -o $(Build.ArtifactStagingDirectory)/pack --configuration Release --version-suffix $dateStr --no-dependencies
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'pack'
      publishLocation: 'Container'

- job: 'PushNuget'
  displayName: Push Git
  dependsOn: Pack
  continueOnError: false 
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/$(projectName)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/$(projectName)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'NuGetOrgConnection'